baseURL = "https://ivodopiviz.github.io/"
disqusShortname = "username"
googleAnalytics = ""
languageCode = "en-us"
theme = "minimal"
title = "ivodopiviz"
[[menu.icon]]
name = "linkedin"
url = "https://www.linkedin.com/in/ivanvodopiviz/"
weight = 4
[[menu.icon]]
name = "twitter"
url = "https://twitter.com/ivodopiviz/"
weight = 3
[[menu.icon]]
name = "github"
url = "https://github.com/ivodopiviz/"
weight = 2
[[menu.icon]]
name = "envelope-o"
url = "mailto:ivanvodo@gmail.com"
weight = 1
[[menu.main]]
name = "Projects"
url = "/project/"
weight = 3
[[menu.main]]
name = "Posts"
url = "/post/"
weight = 2
[[menu.main]]
name = "Home"
url = "/"
weight = 1
[params]
accent = "red"
author = "Calin Tataru"
backgroundcolor = "white"
description = "Personal blog theme powered by Hugo"
font = "Raleway"
githubusername = "#"
highlight = true
highlightlanguages = ["c++"]
highlightstyle = "solarized-dark"
showborder = true
